/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiImgRouteImport } from './routes/api/img'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImgRoute = ApiImgRouteImport.update({
  id: '/api/img',
  path: '/api/img',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/developer': typeof DeveloperRoute
  '/training': typeof TrainingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/img': typeof ApiImgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/developer': typeof DeveloperRoute
  '/training': typeof TrainingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/img': typeof ApiImgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/developer': typeof DeveloperRoute
  '/training': typeof TrainingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/img': typeof ApiImgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/developer'
    | '/training'
    | '/api/chat'
    | '/api/img'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/developer' | '/training' | '/api/chat' | '/api/img'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/developer'
    | '/training'
    | '/api/chat'
    | '/api/img'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DeveloperRoute: typeof DeveloperRoute
  TrainingRoute: typeof TrainingRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiImgRoute: typeof ApiImgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/img': {
      id: '/api/img'
      path: '/api/img'
      fullPath: '/api/img'
      preLoaderRoute: typeof ApiImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DeveloperRoute: DeveloperRoute,
  TrainingRoute: TrainingRoute,
  ApiChatRoute: ApiChatRoute,
  ApiImgRoute: ApiImgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
